version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: ollama/Dockerfile
    ports:
      - "11434:11434"  # Ollama's default port
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    volumes:
      - ./data:/app/data  # If you need to persist data
    
  flask_api:
    build:
      context: .
      dockerfile: flask_api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_PORT=8080
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    depends_on:
      - ollama
